### ISSUE TITLE
Incoming "last-modified" requests

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-caching#2]
+ https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
+ https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since

Clients, upon receiving resources with a `Last-Modified` header, may send requests that contain one or both of the above linked headers. I think handling these headers would be outside the scope of this plugin. At best, I think the incoming request object could be decorated with the values of these headers, e.g.:

```js
fastify.decorateRequest('ifModifiedSince', function () {
  if (!this.req.headers['if-modified-size']) return null
  return new Date(this.req.headers['if-modified-since'])
})
```

Do you agree @fastify?

**Comment by mcollina** [comment]
I would add them as decorators, yes.

Also, I would make them accept a date, like `req.isFresh(lastUpdated)`. It's a piece of common logic that goes kind of everywhere.

**Comment by jsumners** [comment]
How are we expected to know if the resource is fresh? That seems to be application logic to me.

**Comment by mcollina** [comment]
`req.isFresh(lastUpdated)` <-- the `lastUpdated` data is fetched from a DB or the file system.

**Comment by jsumners** [comment]
Okay, I have an idea about that.

**Comment by dougwilson** [comment]
Express / Koa use the `fresh` module for this logic, if that helps at all.

**Comment by jsumners** [comment]
@dougwilson thanks for pointing that out (I'm not an Express guy). It looks like that module relies on the full request before making a decision. That is, you have to fill the response with the resource prior to feeding the module data or it will be unable to make the determination. In my opinion that defeats the purpose. The point is to server the already cached resource so that it does not have to be re-computed.

**Comment by dougwilson** [comment]
Hi @jsumners I'm not sure what you mean; you cannot pass in a `req` or `res` object. It simple takes two objects: the request headers and response headers and will use whatever is available.

**Comment by dougwilson** [comment]
The example at the bottom is simple, showing performing some logic to determine the modified / etag (but not the actual resource) and then not getting the resource if it's still fresh. It just shows a helper as well
```js
function isFresh (req, res) {
  return fresh(req.headers, {
    'etag': res.getHeader('ETag'),
    'last-modified': res.getHeader('Last-Modified')
  })
}
```

Of course you can fill in the etag / last-modified however you want (you don't have to use `res.getHeader` like the example if you don't want). You can also just not include whichever one you don't know as well and the module will just not check that one.

**Comment by jsumners** [comment]
Right, you have to have the response headers before you can use it. And to get the response headers you have to go through the whole request.

**Comment by dougwilson** [comment]
No you don't, that's just an example. You just need to know what the response Etag and or response Last-modified will be. Otherwise how can you check anything?

**Comment by dougwilson** [comment]
For example, given a request, if you look up the ETag (perhaps that is your cache key), and want to know if the client already has that:
```js
var isFresh = fresh(this.req.headers, { etag: etagFromDatabase })
```

You don't need the response object in any way.

**Comment by dougwilson** [comment]
As since this issue is about the last-modified time stamps:
```js
var isFresh = fresh(this.req.headers, { 'last-modified': dateFromDb })
```

Or just pluck the incoming header yourself:
```js
var isFresh = fresh({ 'if-modified-since': this.req.headers['if-modified-since'] }, { 'last-modified': dateFromDb })
```

Anyway, just though you'd want to share in the logic / bug that were built up from all the years of Express / Connect / Koa. I don't mind if you don't use it and / or want to greenfield a new implementation. Just though I'd try to help, but sounds like you'd rather just reject it :(

**Comment by jsumners** [comment]
I am investigating the problem. But the lack of clarity in that module's documentation does not help me understand the usage of that module and thus does not help me understand how it tackles the problem.

**Comment by dougwilson** [comment]
Yea, the docs were written long before I came to help maintain the module, and a lot of the original TJ modules has almost no docs at all, just a line with their name. A lot of them are still on my backlog to flush out the docs for, so any help would be awesome 👍

**Comment by dougwilson** [comment]
Also for that module in particular the API itself is kinda weird (TJ originally wrote it as `fresh(req.headers, res._headers)` but that's not very usable outside of Node.js core applications (and assumed you'd use a private header field). I made some simple docs to just state header objects, but it really is just object with necessary request headers (ideally all, since you'll already have them) and object with the intended response headers related to freshness. I haven't bumped that to 1.0 from the original 0.x mainly because the API is weird, but it has been OK in Express and other TJ-built projects since of course it was built for that. If you think there is a better API, that would be awesome to hear from someone actually trying to use it for a purpose instead of just playing around without any uses for it, which usually leads to poor APIs anyway.

**Comment by jsumners** [comment]
I have opted to ignore the `Last-modified` mechanism and only support the `ETag` mechanism. The ETag standard has been around long enough that web browsers should support it. If the desire it to give the clients a hint to not issue a request to the server, then the `Expires` header can be sent along with the `ETag` header.
