### ISSUE TITLE
Is it possible to set max-age?

### ISSUE THREAD

**Issue by Extarys** [fastify/fastify-caching#22]
I would like to know how to set max-age for a specific path. 
The logo in this example.

```
module.exports = function(fastify, opts, next) {
  fastify.register(require('fastify-caching'))
  fastify.get('/logo.png', handler.logo)
  fastify.get('/nocache.js', handler.js)
}

module.exports = {
  logo: function(request, reply) {
    const stream = fs.createReadStream(
      path.join(appRoot.path, '/build/assets/logo.png'),
      'utf8'
    )
    reply
      .header('Content-Type', 'image/png')
      .send(stream)
  }
  nocache: function(request, reply) {
    const stream = fs.createReadStream(
      path.join(appRoot.path, '/build/assets/nocache.js'),
      'utf8'
    )
    reply
      .header('Content-Type', 'application/javascript; charset=UTF-8')
      .send(stream)
  }
}
```

**Comment by JustinBeaudry** [comment]
@Extarys 

[For Reference](https://github.com/fastify/fastify-caching#api):
> expiresIn (Default: undefined): a value, in seconds, for the max-age the resource may be cached. When this is set, and privacy is not set to no-cache, then ', max-age=<value>' will be appended to the cache-control header.

Yes, you can define a `max-age` in milliseconds. The docs state:
> When this is set, and privacy is not set to no-cache 
but looking at the code this isn't true because [if `privacy` is not defined](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L63) it will fail the `if` condition and will skip the block which applies the `max-age` value from `expiresIn`. [I would suggest setting `privacy` to `public`](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L94) and setting `expiresIn` to your desired `max-age`.

**Comment by Extarys** [comment]
Ohh thanks, I'll look into it! :D
